import { defineAsyncComponent } from 'vue'

export * from './helpers'
export * from './mixins'
export * from './vue-plugin'
export * from './composables'
export * from './plugins'

export const QasActions = defineAsyncComponent(() => import('./components/actions/QasActions.vue'))
export const QasActionsMenu = defineAsyncComponent(() => import('./components/actions-menu/QasActionsMenu.vue'))
export const QasAlert = defineAsyncComponent(() => import('./components/alert/QasAlert.vue'))
export const QasAppBar = defineAsyncComponent(() => import('./components/app-bar/QasAppBar.vue'))
export const QasAppMenu = defineAsyncComponent(() => import('./components/app-menu/QasAppMenu.vue'))
export const QasAppUser = defineAsyncComponent(() => import('./components/app-user/QasAppUser.vue'))
export const QasAvatar = defineAsyncComponent(() => import('./components/avatar/QasAvatar.vue'))
export const QasBadge = defineAsyncComponent(() => import('./components/badge/QasBadge.vue'))
export const QasBoardGenerator = defineAsyncComponent(() => import('./components/board-generator/QasBoardGenerator.vue'))
export const QasBox = defineAsyncComponent(() => import('./components/box/QasBox.vue'))
export const QasBreakline = defineAsyncComponent(() => import('./components/breakline/QasBreakline.vue'))
export const QasBtn = defineAsyncComponent(() => import('./components/btn/QasBtn.vue'))
export const QasBtnDropdown = defineAsyncComponent(() => import('./components/btn-dropdown/QasBtnDropdown.vue'))
export const QasCard = defineAsyncComponent(() => import('./components/card/QasCard.vue'))
export const QasCardImage = defineAsyncComponent(() => import('./components/card-image/QasCardImage.vue'))
export const QasCheckbox = defineAsyncComponent(() => import('./components/checkbox/QasCheckbox.vue'))
export const QasSelectFilter = defineAsyncComponent(() => import('./components/select-filter/QasSelectFilter.vue'))
export const QasCopy = defineAsyncComponent(() => import('./components/copy/QasCopy.vue'))
export const QasDate = defineAsyncComponent(() => import('./components/date/QasDate.vue'))
export const QasDateTimeInput = defineAsyncComponent(() => import('./components/date-time-input/QasDateTimeInput.vue'))
export const QasDebugger = defineAsyncComponent(() => import('./components/debugger/QasDebugger.vue'))
export const QasDelete = defineAsyncComponent(() => import('./components/delete/QasDelete.vue'))
export const QasDialog = defineAsyncComponent(() => import('./components/dialog/QasDialog.vue'))
export const QasDialogRouter = defineAsyncComponent(() => import('./components/dialog-router/QasDialogRouter.vue'))
export const QasDrawer = defineAsyncComponent(() => import('./components/drawer/QasDrawer.vue'))
export const QasEmptyResultText = defineAsyncComponent(() => import('./components/empty-result-text/QasEmptyResultText.vue'))
export const QasErrorMessage = defineAsyncComponent(() => import('./components/error-message/QasErrorMessage.vue'))
export const QasExpansionItem = defineAsyncComponent(() => import('./components/expansion-item/QasExpansionItem.vue'))
export const QasField = defineAsyncComponent(() => import('./components/field/QasField.vue'))
export const QasFilters = defineAsyncComponent(() => import('./components/filters/QasFilters.vue'))
export const QasFormGenerator = defineAsyncComponent(() => import('./components/form-generator/QasFormGenerator.vue'))
export const QasFormView = defineAsyncComponent(() => import('./components/form-view/QasFormView.vue'))
export const QasGallery = defineAsyncComponent(() => import('./components/gallery/QasGallery.vue'))
export const QasGalleryCard = defineAsyncComponent(() => import('./components/gallery-card/QasGalleryCard.vue'))
export const QasGrabbable = defineAsyncComponent(() => import('./components/grabbable/QasGrabbable.vue'))
export const QasGridGenerator = defineAsyncComponent(() => import('./components/grid-generator/QasGridGenerator.vue'))
export const QasGridItem = defineAsyncComponent(() => import('./components/grid-item/QasGridItem.vue'))
export const QasHeader = defineAsyncComponent(() => import('./components/header/QasHeader.vue'))
export const QasInfiniteScroll = defineAsyncComponent(() => import('./components/infinite-scroll/QasInfiniteScroll.vue'))
export const QasInput = defineAsyncComponent(() => import('./components/input/QasInput.vue'))
export const QasLabel = defineAsyncComponent(() => import('./components/label/QasLabel.vue'))
export const QasLayout = defineAsyncComponent(() => import('./components/layout/QasLayout.vue'))
export const QasListItems = defineAsyncComponent(() => import('./components/list-items/QasListItems.vue'))
export const QasListView = defineAsyncComponent(() => import('./components/list-view/QasListView.vue'))
export const QasNestedFields = defineAsyncComponent(() => import('./components/nested-fields/QasNestedFields.vue'))
export const QasNumericInput = defineAsyncComponent(() => import('./components/numeric-input/QasNumericInput.vue'))
export const QasOptionGroup = defineAsyncComponent(() => import('./components/option-group/QasOptionGroup.vue'))
export const QasPageHeader = defineAsyncComponent(() => import('./components/page-header/QasPageHeader.vue'))
export const QasPagination = defineAsyncComponent(() => import('./components/pagination/QasPagination.vue'))
export const QasPasswordInput = defineAsyncComponent(() => import('./components/password-input/QasPasswordInput.vue'))
export const QasPasswordStrengthChecker = defineAsyncComponent(() => import('./components/password-strength-checker/QasPasswordStrengthChecker.vue'))
export const QasProfile = defineAsyncComponent(() => import('./components/profile/QasProfile.vue'))
export const QasResizer = defineAsyncComponent(() => import('./components/resizer/QasResizer.vue'))
export const QasRadio = defineAsyncComponent(() => import('./components/radio/QasRadio.vue'))
export const QasSearchBox = defineAsyncComponent(() => import('./components/search-box/QasSearchBox.vue'))
export const QasSearchInput = defineAsyncComponent(() => import('./components/search-input/QasSearchInput.vue'))
export const QasSelect = defineAsyncComponent(() => import('./components/select/QasSelect.vue'))
export const QasSelectList = defineAsyncComponent(() => import('./components/select-list/QasSelectList.vue'))
export const QasSelectListDialog = defineAsyncComponent(() => import('./components/select-list-dialog/QasSelectListDialog.vue'))
export const QasSignaturePad = defineAsyncComponent(() => import('./components/signature-pad/QasSignaturePad.vue'))
export const QasSignatureUploader = defineAsyncComponent(() => import('./components/signature-uploader/QasSignatureUploader.vue'))
export const QasSingleView = defineAsyncComponent(() => import('./components/single-view/QasSingleView.vue'))
export const QasSortable = defineAsyncComponent(() => import('./components/sortable/QasSortable.vue'))
export const QasStatus = defineAsyncComponent(() => import('./components/status/QasStatus.vue'))
export const QasStepper = defineAsyncComponent(() => import('./components/stepper/QasStepper.vue'))
export const QasStepperFormView = defineAsyncComponent(() => import('./components/stepper-form-view/QasStepperFormView.vue'))
export const QasTableGenerator = defineAsyncComponent(() => import('./components/table-generator/QasTableGenerator.vue'))
export const QasTabsGenerator = defineAsyncComponent(() => import('./components/tabs-generator/QasTabsGenerator.vue'))
export const QasTextTruncate = defineAsyncComponent(() => import('./components/text-truncate/QasTextTruncate.vue'))
export const QasTimeline = defineAsyncComponent(() => import('./components/timeline/QasTimeline.vue'))
export const QasToggle = defineAsyncComponent(() => import('./components/toggle/QasToggle.vue'))
export const QasToggleVisibility = defineAsyncComponent(() => import('./components/toggle-visibility/QasToggleVisibility.vue'))
export const QasTransfer = defineAsyncComponent(() => import('./components/transfer/QasTransfer.vue'))
export const QasTreeGenerator = defineAsyncComponent(() => import('./components/tree-generator/QasTreeGenerator.vue'))
export const QasUploader = defineAsyncComponent(() => import('./components/uploader/QasUploader.vue'))
export const QasWelcome = defineAsyncComponent(() => import('./components/welcome/QasWelcome.vue'))
export const QasWhatsappLink = defineAsyncComponent(() => import('./components/whatsapp-link/QasWhatsappLink.vue'))
