name: asteroid

static_sites:
  - name: v2
    github:
      repo: bildvitta/asteroid
      branch: main
      deploy_on_push: true
    source_dir: ui
    build_command: npm run storybook:build
    output_dir: storybook-static
    routes:
      - path: /
