/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocApi: typeof import('./src/components/DocApi.vue')['default']
    DocApiEntry: typeof import('./src/components/DocApiEntry.vue')['default']
    DocCardTitle: typeof import('./src/components/DocCardTitle.vue')['default']
    DocCode: typeof import('./src/components/DocCode.vue')['default']
    DocCopyButton: typeof import('./src/components/DocCopyButton.vue')['default']
    DocExample: typeof import('./src/components/DocExample.vue')['default']
    DocHeading: typeof import('./src/components/DocHeading.vue')['default']
    DocMenu: typeof import('./src/components/DocMenu.vue')['default']
    DocMenuItem: typeof import('./src/components/DocMenuItem.vue')['default']
    DocNote: typeof import('./src/components/DocNote.vue')['default']
    DocPage: typeof import('./src/components/DocPage.vue')['default']
    DocPrint: typeof import('./src/components/DocPrint.vue')['default']
    DocToken: typeof import('./src/components/DocToken.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
